version: '3.9'

services:
  app3:
    build: .
    container_name: app3-container
    ports:
      - "3002:3000"
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydb
    networks:
      - shared-network
    volumes:
      - ./app3:/usr/src/app
      - /usr/src/app/node_modules

networks:
  shared-network:
    external: true
